name: glacio
channels:
  - conda-forge
dependencies:
  - geopandas
  - ipython
  - matplotlib
  - pdal
  - python-pdal
  - pyproj
  - rasterio
  - richdem
  - scipy
  - tqdm
  - pip
  - pytest
  - pip:
    - "--editable=git+https://github.com/GlacioHack/GeoUtils.git#egg=GeoUtils"
    - "--editable=git+https://github.com/GlacioHack/DemUtils.git#egg=DemUtils"
